using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum LayerEnum
{
    MONSTER_HIT_BOX=8, MONSTER_HURT_BOX, PLAYER_HIT_BOX , PLAYER_HURT_BOX, PLAYER_PROJECTILE, MONSTER_PROJECTILE, OTHER_CLIENT_PLAYER_COLLIDER = 24, OTHER_CLIENT_MONSTER_COLLIDER = 25, DISABLE_BOX =31
}